# Generated by Django 6.0.6 on 2026-07-22 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('books', 'Books & Notebooks'), ('documents', 'Documents & IDs'), ('clothing', 'Clothing & Accessories'), ('keys', 'Keys'), ('bags', 'Bags & Backpacks'), ('other', 'Other')], max_length=30)),
                ('location_found', models.CharField(max_length=200)),
                ('date_found', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='found_items/')),
                ('status', models.CharField(choices=[('unclaimed', 'Unclaimed'), ('claimed', 'Claimed')], default='unclaimed', max_length=15)),
                ('finder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClaimRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proof_description', models.TextField(help_text='Provide details describing how you lost the item or other proof that it belongs to you.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to=settings.AUTH_USER_MODEL)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to='lostfound.founditem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('books', 'Books & Notebooks'), ('documents', 'Documents & IDs'), ('clothing', 'Clothing & Accessories'), ('keys', 'Keys'), ('bags', 'Bags & Backpacks'), ('other', 'Other')], max_length=30)),
                ('location_lost', models.CharField(max_length=200)),
                ('date_lost', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='lost_items/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('matched', 'Matched'), ('closed', 'Closed')], default='open', max_length=15)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
